### ISSUE TITLE
Documentation lacking around how to set resolution of data (e.g. to minute chart)

### ISSUE THREAD

**Issue by kevinkga** [Arction/lcjs-example-0201-ohlc#1]
I've tried a simple data set of 
`
[
  [ 1613130960000,    806.96,    806.96,    806.95,    806.96  ],
  [ 1613131020000,    806.95,    806.95,    806.95,    806.95  ],
  [ 1613131080000,    806.96,    806.96,    806.95,    806.96  ],
  [ 1613131140000,    806.95,    806.96,    806.95,    806.96  ],
  [ 1613131200000,    807.46,    807.96,    806.61,    806.8  ],
  [ 1613131260000,    806.79,    807.96,    806.79,    807.95  ],
  [ 1613131320000,    807.96,    807.96,    806.95,    807.95  ]
]
`

with this example and I keep getting a single candlestick for the day when what I want is to see minute candlesticks. There's dense documentation but nothing that really explains how to use the APIs or libraries.

**Comment by Snekw** [comment]
The axis resolution is limited by floating point accuracy and to allow the use of number ranges where the floating point accuracy would result in incorrect charts we have implemented a method to change the *origin* of the DateTime axis. The idea behind the DateTime axis origin is explained more here: https://www.arction.com/lightningchart-js-interactive-examples/examples/lcjs-example-0021-dateTimeAxisOrigin.html

In your case you can decide to use the first data points time as the origin time.

```js
const originMS = data[0][0]
const dateTimeOrigin = new Date(originMS)
```

With the origin date you can then setup the DateTime axis.

```js
chart
    .getDefaultAxisX()
    // Setup DateTime tick strategy with specific data origin
    .setTickStrategy(
        AxisTickStrategies.DateTime,
        (tickStrategy) => tickStrategy.setDateOrigin(dateTimeOrigin)
    )
```

Then before you add the data to the series you need to remove the originMS offset from the data time values.
```js
// Prepare data, remove the origin offset from data
data.forEach(point => {
    point[0] = point[0] - originMS
})
```
After that you can add the data to a ohlc series.

```js
// add the prepared data to the series
ohlcSeries.add(data)
```

You can copy the following code to the editor at https://www.arction.com/lightningchart-js-interactive-examples/edit/lcjs-example-0202-ohlcPlotAutomaticPacking.html to see the code in action.

```js
const lcjs = require('@arction/lcjs')

const {
    lightningChart,
    AxisTickStrategies,
    OHLCSeriesTypes
} = lcjs

// Decide on an origin for DateTime axis
const origin = 1613130960000
const dateOrigin = new Date(origin)

const chart = lightningChart().ChartXY()

chart
    .getDefaultAxisX()
    // Setup DateTime tick strategy with specific data origin
    .setTickStrategy(
        AxisTickStrategies.DateTime,
        (tickStrategy) => tickStrategy.setDateOrigin(dateOrigin)
    )

// Create ohlc series
const ohlcSeries = chart.addOHLCSeries(
    { seriesConstructor: OHLCSeriesTypes.Normal }
)

// Load data
const data = [[1613130960000, 806.96, 806.96, 806.95, 806.96], [1613131020000, 806.95, 806.95, 806.95, 806.95], [1613131080000, 806.96, 806.96, 806.95, 806.96], [1613131140000, 806.95, 806.96, 806.95, 806.96], [1613131200000, 807.46, 807.96, 806.61, 806.8], [1613131260000, 806.79, 807.96, 806.79, 807.95], [1613131320000, 807.96, 807.96, 806.95, 807.95]]
// Prepare data, remove the origin offset from data
data.forEach(point => {
    point[0] = point[0] - origin
})

// add the prepared data to the series
ohlcSeries.add(data)
```

In future you should direct questions regarding how to use the charts to StackOverflow and use the `lightningchart` tag. That way you will most likely receive answers bit faster. :)

**Comment by kevinkga** [comment]
Thanks for the clarification. This helped a lot and I will direct further questions like this to StackOverflow
